@startuml

() tiles
() "geolines\ngeoshapes" as geoshapes
() "static maps" as staticmaps


package mediawiki {

  [Kartographer]
  [Visual Editor]
  [JSON config] as JSON

  Kartographer --> JSON: get overlay data

}

package browser {

  [leaflet] ..> tiles: <<uses>>
  [leaflet] ..> geoshapes: <<uses>>
  [leaflet] ..> Kartographer: <<served by>>

}

browser ..> staticmaps: <<uses>>

@enduml
