@startuml

oozie -> hadoop: schedule label generation

note left
  arrow signify initiator
  of communication, not
  data flow
end note

== click model generation ==
activate hadoop

database hive
hadoop -> hive: retrieve click data
hadoop -> hive: retrieve query data
hadoop -> hadoop: normalize queries
hadoop -> hadoop: aggregate click data with queries

== feature vector retrieval ==
database kafka
hadoop -> kafka: send normalized queries for feature vectors

relforge -> kafka: retrieve queries to be analyzed
relforge --> kafka: send feature vectors back

hadoop -> kafka: retrieve feature vectors
hadoop -> hive: store query x feature vectors matrix

== machine learning ==
hadoop -> hive: retrieve query x feature vectors matrix
hadoop -> hadoop: create decision trees with xgboost\n
hadoop -> hive: store decision trees
deactivate hadoop

== upload to production ==
actor operator

operator -> hive: retrieve decision trees
operator -> "elasticsearch\ncirrus": upload decision trees to production
note right
 upload to production
 isn't automated yet
end note

@enduml

