@startuml
skinparam handwritten true

Class "Index\n~4k" as Index
note left: user facing abstraction

Class "Shard\n(primary + replicas)\n~12k" as Shard
note left: scalability unit

Class "Segment\n~100k" as Segment
note left: lucene internals

Index "1" *-- "*" Shard
Shard "1" *-- "*" Segment

@enduml